import React, { useState, useEffect } from 'react'
import Header from './components/Header'
import RecommendationCard from './components/RecommendationCard'
import CumulativeImpactWidget from './components/CumulativeImpactWidget'
import ConstructionInputFlow from './components/ConstructionInputFlow'
import BatteryInputFlow from './components/BatteryInputFlow'
import LandingPage from './components/LandingPage'
import { getImpactSummaryApi, resetSessionApi } from './services/api'

// Initial default demonstration card for when the user first loads the app
const INITIAL_DEFAULT_CARD = {
  item: 'Structural Precast Concrete Slab — Sample 1',
  stream: 'construction',
  assessed_condition: 'Pristine, structural-grade precast concrete units with intact compressive integrity.',
  recommended_pathway: 'Reuse',
  confidence: 92.6,
  reasoning:
    'Clean structural-grade concrete elements with zero visible micro-fractures qualify for direct modular reuse or high-specification engineered aggregate in new structural construction, maximizing embodied carbon retention.',
  estimated_value_recovered: '₹5,200 (vs ₹1,600 if crushed for road base)',
  environmental_impact: 'Diverts 100% (~500 kg) from landfill; saves ~420 kg CO₂e embodied carbon.',
  safety_flags: [],
}

export default function App() {
  // Navigation State: determine initial route from window.location.pathname
  const [currentRoute, setCurrentRoute] = useState(() => {
    if (typeof window !== 'undefined' && window.location.pathname === '/app') {
      return '/app'
    }
    return '/'
  })

  const [activeStream, setActiveStream] = useState('construction')
  const [currentAssessment, setCurrentAssessment] = useState(INITIAL_DEFAULT_CARD)
  const [impactData, setImpactData] = useState(null)
  const [errorMessage, setErrorMessage] = useState(null)
  const [isResetting, setIsResetting] = useState(false)

  // Listen to popstate (back/forward browser buttons)
  useEffect(() => {
    const handlePopState = () => {
      const path = window.location.pathname === '/app' ? '/app' : '/'
      setCurrentRoute(path)
    }
    window.addEventListener('popstate', handlePopState)
    return () => window.removeEventListener('popstate', handlePopState)
  }, [])

  // Route navigation helper
  const navigateTo = (path) => {
    setCurrentRoute(path)
    if (typeof window !== 'undefined') {
      window.history.pushState({}, '', path)
      window.scrollTo({ top: 0, behavior: 'smooth' })
    }
  }

  // Fetch cumulative impact metrics from backend
  const fetchImpact = async () => {
    try {
      const data = await getImpactSummaryApi()
      setImpactData(data)
    } catch (err) {
      console.warn('Could not fetch impact summary (backend may be starting):', err)
      setImpactData({
        session_assessments_count: 1,
        formatted_total_value: '₹5,200',
        formatted_total_diverted: '500.0 kg',
        formatted_total_co2: '420.0 kg CO₂e',
        pathway_breakdown: {
          Reuse: 1,
          Refurbishment: 0,
          Repurposing: 0,
          Recycling: 0,
          Disposal: 0,
        },
      })
    }
  }

  useEffect(() => {
    fetchImpact()
  }, [])

  // Callback when an assessment is generated by either module
  const handleAssessmentComplete = (result) => {
    setCurrentAssessment(result)
    setErrorMessage(null)
    fetchImpact() // refresh impact counters
  }

  const handleError = (msg) => {
    setErrorMessage(msg)
  }

  const handleResetSession = async () => {
    setIsResetting(true)
    try {
      await resetSessionApi()
      await fetchImpact()
    } catch (err) {
      console.warn('Reset session notice:', err)
      fetchImpact()
    } finally {
      setIsResetting(false)
    }
  }

  // If on Landing Page route "/"
  if (currentRoute === '/') {
    return <LandingPage onStartAssessment={() => navigateTo('/app')} />
  }

  // Otherwise on Assessment App route "/app"
  return (
    <div className="min-h-screen bg-slate-950 text-slate-100 flex flex-col selection:bg-emerald-500 selection:text-slate-950 font-sans">
      {/* 1. Header with Reset Control and Back to Home Navigation */}
      <Header
        onResetSession={handleResetSession}
        isResetting={isResetting}
        onNavigateHome={() => navigateTo('/')}
      />

      {/* Main Container */}
      <main className="flex-1 max-w-7xl w-full mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-8">
        {/* Navigation Bar / Breadcrumb */}
        <div className="flex items-center justify-between">
          <button
            type="button"
            onClick={() => navigateTo('/')}
            className="inline-flex items-center space-x-2 text-xs font-semibold text-slate-400 hover:text-emerald-400 transition-colors cursor-pointer group"
          >
            <span className="group-hover:-translate-x-1 transition-transform">←</span>
            <span>Back to Home</span>
          </button>
          <span className="text-xs text-slate-500 font-medium">
            Step-by-step Triage Wizard
          </span>
        </div>

        {/* Error Notification Banner */}
        {errorMessage && (
          <div className="p-4 rounded-xl bg-rose-950/80 border border-rose-800/80 text-rose-200 text-xs flex items-center justify-between shadow-lg">
            <div className="flex items-center space-x-2">
              <span className="text-base">⚠️</span>
              <span>{errorMessage}</span>
            </div>
            <button
              onClick={() => setErrorMessage(null)}
              className="text-rose-400 hover:text-white text-sm font-bold px-2 cursor-pointer"
            >
              ✕
            </button>
          </div>
        )}

        {/* 2. Stream Switcher Tabs: Construction Debris vs EV Battery */}
        <div className="flex flex-col sm:flex-row items-stretch sm:items-center justify-between gap-4 bg-slate-900/60 p-2 rounded-2xl border border-slate-800 backdrop-blur-md">
          <div className="grid grid-cols-2 gap-2 flex-1">
            {/* Stream A Tab */}
            <button
              type="button"
              onClick={() => setActiveStream('construction')}
              className={`flex items-center justify-center space-x-3 px-5 py-3.5 rounded-xl font-bold text-sm transition-all duration-200 cursor-pointer ${
                activeStream === 'construction'
                  ? 'bg-gradient-to-r from-emerald-600 to-teal-600 text-white shadow-lg shadow-emerald-950/50 ring-1 ring-emerald-400/30'
                  : 'bg-slate-900/80 text-slate-400 hover:text-slate-200 hover:bg-slate-800/80'
              }`}
            >
              <span className="text-xl">🏗️</span>
              <div className="text-left leading-tight">
                <div>Construction Material</div>
                <span className="text-[11px] font-normal opacity-80">Concrete, Brick, Wood, Steel & Rubble</span>
              </div>
            </button>

            {/* Stream B Tab */}
            <button
              type="button"
              onClick={() => setActiveStream('battery')}
              className={`flex items-center justify-center space-x-3 px-5 py-3.5 rounded-xl font-bold text-sm transition-all duration-200 cursor-pointer ${
                activeStream === 'battery'
                  ? 'bg-gradient-to-r from-cyan-600 to-blue-600 text-white shadow-lg shadow-cyan-950/50 ring-1 ring-cyan-400/30'
                  : 'bg-slate-900/80 text-slate-400 hover:text-slate-200 hover:bg-slate-800/80'
              }`}
            >
              <span className="text-xl">⚡</span>
              <div className="text-left leading-tight">
                <div>EV Battery Pack</div>
                <span className="text-[11px] font-normal opacity-80">NMC, LFP, Capacity & Degradation Triage</span>
              </div>
            </button>
          </div>
        </div>

        {/* 3. Main Split Dashboard Grid */}
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start">
          {/* Left Column: Interactive Form Flows & Impact Counter */}
          <div className="lg:col-span-5 space-y-6">
            {activeStream === 'construction' ? (
              /* Stream A: Full Interactive Construction Input Flow */
              <ConstructionInputFlow
                onAssessmentComplete={handleAssessmentComplete}
                onError={handleError}
              />
            ) : (
              /* Stream B: Full Interactive EV Battery Input Flow */
              <BatteryInputFlow
                onAssessmentComplete={handleAssessmentComplete}
                onError={handleError}
              />
            )}

            {/* Cumulative Impact Widget */}
            <CumulativeImpactWidget impactData={impactData} onReset={fetchImpact} />
          </div>

          {/* Right Column: Shared Unified Recommendation Card */}
          <div className="lg:col-span-7 space-y-4">
            <div className="flex items-center justify-between px-1">
              <div className="flex items-center space-x-2">
                <span className="text-xs font-bold uppercase tracking-wider text-slate-400">
                  Recommendation Output
                </span>
              </div>
            </div>

            {/* Reusable Shared Recommendation Card */}
            <RecommendationCard assessment={currentAssessment} />
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-slate-800/80 bg-slate-950/90 py-6 text-center text-xs text-slate-500">
        <div className="max-w-7xl mx-auto px-4 flex flex-col sm:flex-row items-center justify-between gap-2">
          <span>ReVolve — Circular Waste-Recovery Platform &copy; Smart India Hackathon</span>
          <span className="text-slate-600">Built for Smart India Hackathon</span>
        </div>
      </footer>
    </div>
  )
}

